name: xmpp_iq
version: 0.1.0
description: XMPP IQ stanza caller and callee handlers.

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  xmpp_id: ^0.1.0
  xmpp_events: ^0.1.0
  xmpp_xml: ^0.1.0
  xmpp_middleware: ^0.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
