name: xmpp_jid
description: XMPP JID (Jabber ID) parsing and manipulation
version: 0.1.0
repository: https://github.com/xmppjs/xmpp.dart/tree/main/packages/xmpp_jid

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
