name: xmpp_sasl_anonymous
version: 0.1.0
description: SASL ANONYMOUS mechanism for XMPP authentication.

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  xmpp_sasl: ^0.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
