name: xmpp_stanza
description: Base stanza classes for XMPP - Message, Presence, and custom stanza support
version: 0.1.0

resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  xml: ^6.3.0
  xmpp_jid: ^0.1.0
  xmpp_xml: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
  talker: ^5.1.2
  test: ^1.24.0
  xmpp: ^0.1.0
